version: "3.7"

services:
  dspace:
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-5_x-jdk8-test}"
    volumes:
      - "../../add-ons/mirage2/xmlui.xconf:/dspace/config/xmlui.xconf"
      - "solr_authority:/dspace/solr/authority/data"
      - "solr_oai:/dspace/solr/oai/data"
      - "solr_search:/dspace/solr/search/data"
      - "solr_statistics:/dspace/solr/statistics/data"
    environment:
      - SCRIPTVER=5
