version: "3.7"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    # Note that a separate image exists for DSpace 4x
    # image: dspace/dspace-postgres-4x
    container_name: dspacedb
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
      - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-6_x-jdk8-test}"
    container_name: dspace
    environment:
      - DSPACE_INSTALL=/dspace
      - ADMIN_EMAIL=${ADMIN_EMAIL:-test@test.edu}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
      - ADMIN_FNAME=${ADMIN_FNAME:-AdminFirst}
      - ADMIN_LNAME=${ADMIN_LNAME:-AdminLast}
      - AIPZIP=${AIPZIP:-https://github.com/DSpace-Labs/AIP-Files/raw/master/dogAndReport.zip}
    ports:
      - 8080:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "solr:/dspace/solr"
      - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    entrypoint: chmod 755 /dspace-docker-tools/*.sh && /dspace-docker-tools/ingestAIP.sh
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

volumes:
  pgdata:
  assetstore:
  solr:

networks:
  dspacenet:
