version: "3.7"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    # Note that a separate image exists for DSpace 4x
    # image: dspace/dspace-postgres-4x
    container_name: dspacedb
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
      - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "${DOCKER_OWNER:-dspace}/dspace:${DSPACE_VER:-dspace-6_x-jdk8-test}"
    container_name: dspace
    environment:
      - DSPACE_INSTALL=/dspace
      - ADMIN_EMAIL=${ADMIN_EMAIL:-test@test.edu}
      - ADMIN_PASS=${ADMIN_PASS:-admin}
      - ADMIN_FNAME=${ADMIN_FNAME:-AdminFirst}
      - ADMIN_LNAME=${ADMIN_LNAME:-AdminLast}
      - AIPZIP=${AIPZIP:-https://github.com/DSpace-Labs/AIP-Files/raw/master/dogAndReport.zip}
      # export SKIPAIP=Y
      - SKIPAIP=${SKIPAIP:-N}
      # Number of sec to wait before attempting AIP ingest
      - AIPWAIT=0
      # Number of sec to wait before attempting to start tomcat
      - DBWAIT=0
      - LOCALCFG1=
        \n# LOCALCFG1 overrides
      - LOCALCFG2=
        \n# LOCALCFG2 overrides
      - LOCALCFG3=
        \n# LOCALCFG3 overrides
    ports:
      - ${PORT:-8080}:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "../../add-ons/dspace-docker-tools:/dspace-docker-tools"
    entrypoint: /dspace-docker-tools/ingestAIP.sh
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true

volumes:
  pgdata:
  assetstore:
  # The Solr volumes will be defined in one of the dX.override.yml files
  solr_authority:
  solr_oai:
  solr_search:
  solr_statistics:

networks:
  dspacenet:
